### ISSUE TITLE
sites near the top of the map do not respond to clicks

### ISSUE THREAD

**Issue by gubuntu** [kartoza/django-bims#242] opened 2018-08-18 13:29 UTC

**Comment by dimasciput** [comment] 2018-08-29 01:44
couldn't reproduce anymore in testing, maybe it has been fixed

**Comment by Vries14** [comment] 2018-08-30 08:01
Sites at the top of the map are responding to clicks. Im closing the issue.

**Comment by Vries14** [comment] 2018-09-04 09:29
Looks like it has been fixed, they are responding to clicks. I'm closing the isssue.

**Closed by Vries14** 2018-09-04 09:29 UTC
Labels: bug, testing
