### ISSUE TITLE
Hide FBIS Users from the San Parks Django admin 

### ISSUE THREAD

**Issue by amyburness** [kartoza/django-bims#3830] opened 2024-04-16 09:29 UTC
Currently, we can see all the FBIS users under Users. Sanparks should only see the Sanparks users. 

We should also discuss users who have logins for both platforms and how we handle it.

**Comment by dimasciput** [comment] 2024-04-30 08:29
Duplicate of https://github.com/kartoza/django-bims/issues/3841. Closing this one

**Closed by dimasciput** 2024-04-30 08:29 UTC
Labels: discussion, SANParks Instance
