### ISSUE TITLE
URL not showing in metadata

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1868] opened 2020-01-28 12:33 UTC
- http://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=Baetis%20harrisoni&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=21&validated=["validated"]&sourceCollection=["fbis"]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name

**Comment by dimasciput** [comment] 2020-02-04 03:22
@jeremyshelton yes they are data from biobase table, they don't have doi, so there's no url. 

This is sample data from BioReference table : 
<table><tr><th colspan="10">BioReference</th></tr><tr><th>BioReferenceID</th><th>Author</th><th>Year</th><th>Title</th><th>Journal</th><th>OriginalReference</th><th>User</th><th>DateFrom</th><th>DateModified</th><th>DateTo</th></tr><tr class="odd"><td>fa90b1a2-161e-4d51-90f0-8725dc7a07e1</td><td>Harrison A.D. &amp; Elsworth J.F</td><td>1958</td><td>Hydrobiological  studies of the  Great Berg River; Part 1. General description of chemical studies and main features of the flora and fauna.</td><td>Transactions of the Royal Society of South Africa Vol 35. Part  3: pp.125-226.</td><td>1</td><td>952d4f51-118a-4550-8c05-4140c5264708</td><td>2009-09-30</td><td>2009-09-30</td><td>&nbsp;</td></tr>
  <tr><td>8b729bd5-dcee-41e6-b552-d49ddb479405</td><td>Kemp P.H. Chutter F.M. &amp; Coetzee D.J.</td><td>1976</td><td>Water  quality and abatement of pollution  in Natal rivers. Part V: The rivers of southern Natal.</td><td>National Institute for Water Research, CSIR and the Town and Regional  Planning Commission Report.</td><td>2</td><td>952d4f51-118a-4550-8c05-4140c5264708</td><td>2009-09-30</td><td>2009-09-30</td><td>&nbsp;</td></tr>
  <tr class="odd"><td>bd6ed3f8-86f0-411c-b34e-2d5ffff402a0</td><td>Harrison A.D.</td><td>1958A</td><td>Hydrobiological studies of the Great Berg River, Western Cape Province. Part 2: Quantitative studies on sandy bottoms, notes on tributaries and further information on the fauna, arranged systematically.</td><td>Transactions of the Royal Society of South Africa Vol 35. Part 2: pp. 227-276.</td><td>3</td><td>952d4f51-118a-4550-8c05-4140c5264708</td><td>2009-09-30</td><td>2009-09-30</td><td>&nbsp;</td></tr>
  <tr><td>dc4be810-2aa4-4415-aca7-0f1c96b5196b</td><td>Moore C.A. &amp; Chutter F.M.</td><td>1988</td><td>A survey of the conservation status and  benthic biota of the major rivers of the Kruger National Park.</td><td>CSIR and National Institute for Water Research (NIWR) Contract report, Pretoria.</td><td>4</td><td>952d4f51-118a-4550-8c05-4140c5264708</td><td>2009-09-30</td><td>2009-09-30</td><td>&nbsp;</td></tr>
  <tr class="odd"><td>73195b90-b3fb-45ea-beb6-2a53cc5553d8</td><td>Wilkinson R.C.</td><td>1979</td><td>The indicator value of the stones-in-current fauna of the Jukskei-Crocodile river system, Transvaal, South Africa.</td><td>MSc thesis. Zoology Department, University of Pretoria, South Africa.</td><td>5</td><td>952d4f51-118a-4550-8c05-4140c5264708</td><td>2009-09-30</td><td>2009-09-30</td><td>&nbsp;</td></tr>
  <tr><td>0d995759-fa99-4360-9d7d-d5b7c3710306</td><td>Fowles B.K. Butler A.C. Brown H.M. Kemp P.H. Coetzee O.J. &amp; Metz  H.</td><td>1979</td><td>Water quality and abatement of pollution in Natal Rivers. Part VII. Special studies in the rapidly developing areas of Newcastle and Ladysmith.</td><td>National Institute for Water Research, CSIR and the Town and Regional  Planning Commission Report.</td><td>6</td><td>952d4f51-118a-4550-8c05-4140c5264708</td><td>2009-09-30</td><td>2009-09-30</td><td>&nbsp;</td></tr>
   <tr class="odd"><td>69667ee3-2c11-42a5-8394-d83dc3ea2281</td><td>O'Keeffe J.H.</td><td>1990</td><td>Kubusi River ecological assessment. A preliminary assessment of the Kubusi River at Wriggleswade with recommendations for the operation of Wriggleswade so as to minimise disruption downstream.</td><td>Unpublished report for the Department of Water Affairs.</td><td>7</td><td>952d4f51-118a-4550-8c05-4140c5264708</td><td>2009-09-30</td><td>2009-09-30</td><td>&nbsp;</td></tr>
  <tr><td>86892801-05b2-477a-b259-aac88d96238b</td><td>O'Keeffe J.H.</td><td>1987</td><td>Ecological impacts of an interbasin transfer of water to the Yellowwoods River (Eastern Cape Province) : A preliminary assessment.</td><td>Unpublished report: Institute for Freshwater Studies, Rhodes University, South Africa.</td><td>8</td><td>952d4f51-118a-4550-8c05-4140c5264708</td><td>2009-09-30</td><td>2009-09-30</td><td>&nbsp;</td></tr>
  <tr class="odd"><td>6c75a302-aa88-4ede-871d-39811ca65d0c</td><td>Anonymous</td><td>1966</td><td>Hidrochemie van die belangrikste vrystaatse riviere.</td><td>Nasionale Instituut vir Waternavorsing wetenskaplike en nywerheidsnavorsingsraad.  WNNR Navorsingsverslag Nr. 252. pp1-179.</td><td>9</td><td>952d4f51-118a-4550-8c05-4140c5264708</td><td>2009-09-30</td><td>2009-09-30</td><td>&nbsp;</td></tr>
 </table>

**Comment by jeremyshelton** [comment] 2020-02-04 04:28
@dimasciput OK, does that mean that the DOI/URL column for these bio base studies is blank in the spreadsheet? 

@helendallas would you expect these studies to have the URL/DOI field populated? I googled the first study in this list and found that it does seem to have  DOI: https://www.tandfonline.com/doi/abs/10.1080/00359195809520025

@Aneri16

**Comment by dimasciput** [comment] 2020-02-04 05:51
@jeremyshelton yes the doi column will be blank, we can't search DOI from the reference title. Unless you want to add them manually.

**Comment by jeremyshelton** [comment] 2020-02-12 08:48
@helendallas thoughts on DOI like for the biobase studies?

**Comment by helendallas** [comment] 2020-02-13 12:32
@dimasciput -  please can you indicate which of the Biobase study references are blank. Please confirm the best way to add the missing metadata - see ticket #1895 

@Janette-Lumley  - please can you then add the missing DOIs, URLs and upload the documents as per the protocol.

**Comment by jeremyshelton** [comment] 2020-03-06 04:19
@Janette-Lumley how far along are we with adding the missing URL and DOI data as per #1895
Must we leave this ticket open?

**Comment by Janette-Lumley** [comment] 2020-03-06 06:30
@jeremyshelton I have added everything I could find, will double check with Helen before closing the ticket.

**Comment by helendallas** [comment] 2020-03-06 07:22
@Janette-Lumley Have you added them into the **freshwaterbiodiversity.org** or just to the Biobase excel table?

@dimasciput There was an issue assigning a reference which I am not sure has been resolved. See ticket #1895

**Comment by dimasciput** [comment] 2020-03-06 07:29
@helendallas yes I fixed the bibliography pages, now you can add doi and url from there : https://freshwaterbiodiversity.org/bibliography/
But you can't still link the references to uploaded document.

**Comment by Janette-Lumley** [comment] 2020-03-06 07:33
@helendallas just the excel spreadsheet.

**Comment by dimasciput** [comment] 2020-03-06 07:41
@Janette-Lumley if the problem is missing doi can you fix it here : https://freshwaterbiodiversity.org/bibliography/

**Comment by helendallas** [comment] 2020-03-06 08:28
@Janette-Lumley please can you add them to the live site. @Aneri16 please can you help if @Janette-Lumley is unclear. Keep a record on the spreadsheet what has been uploaded to FBIS.  Also remember to only upload pdf of those not available on the internet.

**Comment by helendallas** [comment] 2020-03-06 08:31
@dimasciput I tried to find the Biobase study references but they do not come up: I tried searching for Harrison
Coetzer
Allanson

Should all be visible, but they are not. Please check
@Janette-Lumley hold off until Dimas gets back to us.

**Comment by dimasciput** [comment] 2020-03-06 08:34
@helendallas use author filter in the left panel if you want to search by author

![image](https://user-images.githubusercontent.com/1979569/76066318-f8748700-5fbf-11ea-9a9f-d974a9828c70.png)

The search bar is only for journal name/title

**Comment by helendallas** [comment] 2020-03-06 08:41
@dimasciput Tahnks, that works. After adding the DOI and hit Save, I don't go back to the screen I started on, and cant find my way back. Can you fix this please.

I end up here: 
![Screenshot_2020-03-06 Select Entry to change Django site admin](https://user-images.githubusercontent.com/45286876/76066811-f9dd8980-5f96-11ea-8906-fececc467e21.png)

@Janette-Lumley easiest is to search on date, then navigate to correct reference and edit.

**Comment by dimasciput** [comment] 2020-03-06 08:43
@helendallas for now maybe right click on the button, then `Open link in new tab`. Because this is only for admin user.

**Comment by helendallas** [comment] 2020-03-06 08:43
@dimasciput Can you also make it visible from the Administration/Documents  - I cant find how to get to the place we arrive when hitting:
 https://freshwaterbiodiversity.org/bibliography/

**Comment by dimasciput** [comment] 2020-03-06 08:44
I added a filter called `DOI exists`, choose false if you want to display all references that doesn't have DOI.

**Comment by dimasciput** [comment] 2020-03-06 08:44
@helendallas choose Citation

**Comment by helendallas** [comment] 2020-03-06 09:07
@dimasciput thanks

**Comment by Janette-Lumley** [comment] 2020-03-06 09:34
@helendallas I have added the DOI and URL's from the spreadsheet (saved to dropbox - "Biobase Study Reference Table For DOI URL - 06-03-20" ) I could only edit using your login on FBIS.

**Comment by jeremyshelton** [comment] 2020-03-07 20:45
Thanks @Janette-Lumley 
@dimasciput what admin level would Janette need to edit these kinds of things directly from her account?

**Comment by dimasciput** [comment] 2020-03-09 05:29
Currently only admin can edit this.

**Comment by jeremyshelton** [comment] 2020-03-09 05:46
OK thanks @dimasciput

**Comment by timlinux** [comment] 2020-03-18 10:40
See #1887  - URLs etc should appear after that is done.

**Comment by helendallas** [comment] 2020-04-17 07:45
@dimasciput 
The filter to search for pubications with a missing DOI, should include URL, as some of the publications have URLs not DOIs.

I am going to create a new ticket for this specifically around Citations and  lose this one.

**Closed by helendallas** 2020-04-17 07:45 UTC
Labels: Data, FRC, Metadata
