### ISSUE TITLE
Lassor tool not workig

### ISSUE THREAD

**Issue by mmindje** [kartoza/django-bims#3354] opened 2023-04-03 09:25 UTC
Dear @dimasciput - The layer selecter seems not to work for the RBIS. Any help?

Thank you

![image](https://user-images.githubusercontent.com/64961274/229747563-81d21ad0-18ad-4360-8d84-d153cccfbd6a.png)

**Comment by dimasciput** [comment] 2023-04-04 08:49
Hi @mmindje can you share the screenshot again?

**Comment by mmindje** [comment] 2023-04-04 09:21
here is it

![image](https://user-images.githubusercontent.com/64961274/229747464-75a403e7-09b0-4eb8-b32a-813b2fdb397b.png)

**Comment by mmindje** [comment] 2023-04-04 09:22
> Hi @mmindje can you share the screenshot again?

Share again in the first message. Thank you

**Comment by mmindje** [comment] 2023-04-13 12:44
> Hi @mmindje can you share the screenshot again?

Hello Dimas, 
I think the layers are still not working. Please check if you can help us. We are presenting the system tomorrow in a meeting and we are afraid to not be able to do so with some functions not working. 

It means the layers in the layer selectors are not working if  you tick or untick them

**Comment by dimasciput** [comment] 2023-05-04 07:41
I have tested on RBIS site and it's working as intended. I'm going to close this one, feel free to reopen the ticket if the issue persists.

**Closed by dimasciput** 2023-05-04 07:41 UTC
Labels: bug
