### ISSUE TITLE
Issue uploading certain taxa in Upload occurrence data

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3284] opened 2022-12-15 11:00 UTC
Examples:

SubFamily Tanytarsini 
SubSpecies Pseudagrion spernatum natalense

Both taxa are in the Taxon table but do upload. and come back in the error file.

**Comment by helendallas** [comment] 2022-12-16 07:19
@dimasciput No its not, I have checked. for examples above the rank is correct but it is not uploading. I have tried several times.

SubFamily Tanytarsini
SubSpecies Pseudagrion spernatum natalense

I even tried as Sub Species and SubSpecies. 

Still not uploading.

I must be missing something???

**Comment by dimasciput** [comment] 2022-12-16 07:32
@helendallas I checked from taxa management, and they does not exists. Can you add them first? 
Did you upload these taxa? 

I tested on testing.

**Comment by helendallas** [comment] 2022-12-16 07:37
They do exist

![image](https://user-images.githubusercontent.com/45286876/208047174-a1053201-ae73-43fd-b2c8-615d833a42b9.png)

![image](https://user-images.githubusercontent.com/45286876/208047469-f15a617e-9d8e-466f-bdd0-aed7ca26ffe5.png)

They are just not visible in the front end....issue from other ticket that is urgent to fix.

**Comment by helendallas** [comment] 2022-12-16 07:41
On production

**Comment by dimasciput** [comment] 2022-12-16 07:43
@helendallas did you upload them before? Sometimes they do exists but not attached to any of the taxon modules. Because they are removed from the module or they are just related to other taxa that are in the module.

**Comment by dimasciput** [comment] 2022-12-16 07:45
I just checked the backend, and they are not associated with any taxon modules. If you uploaded this data before then it is a bug. But if this data is imported or created because it's related to another taxon, then it's not a bug.

**Comment by dimasciput** [comment] 2022-12-16 07:48
@helendallas 
> They are just not visible in the front end....issue from other ticket that is urgent to fix.

This is fixed on testing, but it's different issue actually. Can you give it a try on testing?

**Comment by helendallas** [comment] 2022-12-16 07:50
I uploaded them using the Taxon Management front end. 100% sure it was to invertebrates. So must be a bug.

**Comment by helendallas** [comment] 2022-12-16 08:02
this one Pseudagrion spernatum natalense was imported with the odonates adult master list back in 2020, but tanytarsini was added more recently.

**Comment by dimasciput** [comment] 2022-12-16 08:07
@helendallas can you try on testing for tanytarsini ? see if you get the same error.

> this one Pseudagrion spernatum natalense was imported with the odonates adult master list back in 2020

If you still have the list, we could do re-import to fix these issues. Because we have improved our taxa system from 2020, so we might have better data now.

**Comment by helendallas** [comment] 2022-12-16 08:27
Could this be because Pseudagrion spernatum natalense was uploaded for Odonates adult, but now I am trying to add data for Invertebrates?

Tanytarsini also not visible on testing - uploaded error file but got another error file - attached.

[Uploading error_De_Moor__Barber-James_2003_Kabouga_4otci9R.xlsx…]()

**Comment by helendallas** [comment] 2022-12-16 08:27
Could this be because Pseudagrion spernatum natalense was uploaded for Odonates adult, but now I am trying to add data for Invertebrates?

Tanytarsini also not visible on testing - uploaded error file but got another error file - attached.

[error_De_Moor__Barber-James_2003_Kabouga_4otci9R.xlsx](https://github.com/kartoza/django-bims/files/10243950/error_De_Moor__Barber-James_2003_Kabouga_4otci9R.xlsx)

**Comment by dimasciput** [comment] 2022-12-16 08:39
> Tanytarsini also not visible on testing - uploaded error file but got another error file - attached.

This species is not exists in our system, please add it first.

**Comment by helendallas** [comment] 2022-12-16 08:41
But it is in the taxa table?????

**Comment by dimasciput** [comment] 2022-12-16 08:42
https://testing.healthyrivers.kartoza.com/admin/bims/taxonomy/?q=Tanytarsini

@helendallas not on testing

**Comment by helendallas** [comment] 2023-02-15 06:33
@dimasciput Owrking on testing, please deploy to production

**Comment by dimasciput** [comment] 2023-03-29 09:33
Deployed to production

**Closed by dimasciput** 2023-03-29 09:33 UTC
Labels: SIZE 1, Checked by FRC, Taxon Management, Urgent Priority 1, Deploy to live
