### ISSUE TITLE
Existing FBIS site codes not recognized in new occurrence data upload

### ISSUE THREAD

**Issue by aneriswanepoel** [kartoza/django-bims#2697] opened 2021-07-22 12:24 UTC
Occurrence data uploaded for two existing sites X2CROC-MALEL & X2CROC-NKONG but new sites created instead of the new data being linked to the existing sites (which is what is supposed to happen).

@helendallas @jeremyshelton

**Comment by dimasciput** [comment] 2021-07-28 04:47
@aneriswanepoel did you test it on testing or live site? can you send me the file please

**Comment by jeremyshelton** [comment] 2021-07-28 04:51
@dimasciput this was on testing site. 
@aneriswanepoel will send file through shortly.

**Comment by dimasciput** [comment] 2021-07-28 04:52
@aneriswanepoel @jeremyshelton with the current system, if they have different coordinate (lat, lon). The system will create a new site instead. So do you want to remove the old sites?

**Comment by jeremyshelton** [comment] 2021-07-28 04:55
@dimasciput the new data should be added to the existing site if (1) the FBIS site code is specified in the data upload template and/or (2) they have the same coordinates as an existing site.

@aneriswanepoel @helendallas

**Comment by jeremyshelton** [comment] 2021-07-28 05:16
@dimas here is an example of a spreadsheet that was uploaded to testing but existing FBIS codes were not combined with existing sites with the same site codes, which is what should happen.

[5. IA Russell PhD for uploading.csv](https://github.com/kartoza/django-bims/files/6890481/5.IA.Russell.PhD.for.uploading.csv)

@aneriswanepoel

**Comment by dimasciput** [comment] 2021-07-28 05:33
@jeremyshelton I just checked, and the site from the csv has coordinate (-25.4575, 31.53556) whereas the existing site has coordinate (-25.486, 31.502). So what should system do? Merge the sites, and use the updated coordinate?

**Comment by jeremyshelton** [comment] 2021-07-28 05:47
@dimasciput I think the logic when uploading new data should be:
Merge sites when:
1. FBIS site codes are specified in the upload CSV. But the original site coordinates should be used (not updated with the new ones).
2. Or, when the coordinates in the uploaded CSV match those of an existing site.

**Comment by dimasciput** [comment] 2021-07-28 07:29
This is fixed on testing

**Comment by jeremyshelton** [comment] 2021-07-28 08:51
Thanks @dimasciput. 
We have tested issues 1 and 2 on testing site. 
**Issue 1** is now fixed. Thank you.
**Issue 2** is not. When we uploaded a new record (without FBIS site code) with the same coordinates as an existing FBIS site, a new site is created instead of the new one being merged with the existing one. 
@aneriswanepoel

**Comment by jeremyshelton** [comment] 2021-07-28 09:06
From @aneriswanepoel : So it seems like FBIS will pull the code if its in the spreadsheet, but doesn't recognize coordinates that belong to an existing site 🤔

**Comment by dimasciput** [comment] 2021-07-28 09:09
The coordinate need to be exact the same @jeremyshelton, can you give me the lat and lon for the site.

**Comment by aneriswanepoel** [comment] 2021-07-28 09:18
@dimasciput 

This is the existing code on FBIS:
![image](https://user-images.githubusercontent.com/55532903/127297188-614a45d0-dc5d-44c4-a456-1be58c97ed8a.png)

Co-ordinates in the spreadsheet are identical:
[FBIS testing dummy sheet - new.xlsx](https://github.com/kartoza/django-bims/files/6891793/FBIS.testing.dummy.sheet.-.new.xlsx)

**Comment by jeremyshelton** [comment] 2021-07-28 10:54
@dimasciput let us know if you are able to resolve this issue?
The we can test it on testing and deploy this functionality to live site.
Thanks.

**Comment by dimasciput** [comment] 2021-07-29 09:16
@jeremyshelton @aneriswanepoel please try again on testing

**Comment by aneriswanepoel** [comment] 2021-07-29 09:38
@dimasciput @jeremyshelton yes it's working now

**Comment by jeremyshelton** [comment] 2021-07-29 10:10
Thanks @dimasciput 

Please roll this new data upload functionality (both the site code and site coordinate fixes) out to the live site & let us know when that's done.

@aneriswanepoel

**Comment by dimasciput** [comment] 2021-07-30 02:18
@jeremyshelton @aneriswanepoel 
Deployed to live site.

**Comment by jeremyshelton** [comment] 2021-07-30 03:28
Thanks @dimasciput 
Good work.

**Comment by jeremyshelton** [comment] 2021-08-02 06:51
@dimasciput this is not working on live site. Did you deploy the upload fixes from testing to live?
We uploaded a spreadsheet (see below) to live site and the site codes were not pulled through. New sites were incorrectly created, instead of the sites being merged with the existing sites with the same codes. 

So we now need to (1) remove these data and (2) re-upload them once you confirm that this functionality is fixed on live site. 

@aneriswanepoel 

[1. KNP fish data 2009 for uploading.csv](https://github.com/kartoza/django-bims/files/6914906/1.KNP.fish.data.2009.for.uploading.csv)

**Comment by helendallas** [comment] 2021-08-02 06:59
@jeremyshelton Agreed this functionality need to be working, but for the data already uploaded there is a work around to use the Merge Site functionality. On the Lasso tool.  It may be faster than deleting all the data and reuploading.

**Comment by jeremyshelton** [comment] 2021-08-02 07:04
OK thanks @helendallas 
@aneriswanepoel how many sites would we need to do this for?

**Comment by dimasciput** [comment] 2021-08-02 07:19
> @dimasciput this is not working on live site. Did you deploy the upload fixes from testing to live?

I just checked, and it is updated. Let me quickly restart the server.

**Comment by aneriswanepoel** [comment] 2021-08-02 07:21
> OK thanks @helendallas
> @aneriswanepoel how many sites would we need to do this for?

Looks like its about 12 sites

**Comment by helendallas** [comment] 2021-08-03 11:46
@aneriswanepoel Please can you check if this functionality is working on the live site and revert

**Comment by aneriswanepoel** [comment] 2021-08-03 13:11
@helendallas no does not seem to be working

**Comment by dimasciput** [comment] 2021-08-04 02:07
@aneriswanepoel @helendallas have you tested it again yesterday?

**Comment by aneriswanepoel** [comment] 2021-08-04 05:54
@dimasciput yes tried it yesterday and again this morning and still not working

**Comment by dimasciput** [comment] 2021-08-04 06:06
@aneriswanepoel can you send me the file?

**Comment by dimasciput** [comment] 2021-08-04 06:12
@aneriswanepoel what was the issue? existing site code or coordinate?

**Comment by aneriswanepoel** [comment] 2021-08-04 06:14
@dimasciput issue is existing site code specified in spreadsheet but not pulled onto FBIS

**Comment by dimasciput** [comment] 2021-08-04 06:15
@aneriswanepoel which site code?

**Comment by aneriswanepoel** [comment] 2021-08-04 06:25
@dimasciput so for example B7OLIF-00205 should be B7OLIF-MAMBA because that is what was specified in the spreadsheet. But maybe the issue is the co-ordinates aren't exactly the same?

For this set of data that I have been uploading @helendallas and I agreed that it's fine if new codes are generated because a lot of the data is old and might not be 100% accurate in terms of site codes. 

But for future would be good to have this issue sorted out.

**Comment by helendallas** [comment] 2021-08-12 06:57
@dimasciput This really needs to get fixed.
I uploaded invert data yesterday and all had FBIS Site codes, but only half have been retained

![image](https://user-images.githubusercontent.com/45286876/129151683-33d4a9e1-2b45-44e4-8288-383f79903144.png)

Here the xls fine
[Dallas H. and Day J. 1992.xlsx](https://github.com/kartoza/django-bims/files/6973376/Dallas.H.and.Day.J.1992.xlsx)

**Comment by helendallas** [comment] 2021-08-16 08:07
@dimasciput When will you be able to fix this. It is holding up a lot of our work. If the Site Code in the upload file matches an existing FBIS Site code, then the uploaded data should be added to the existing site. 

See this link, all these data I uploaded have been given new site codes, instead of linking to existing site codes. This functionality was working, so I am not sure why it is problematic now.

https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%22888%22]&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=


Please find time to do this asap. Thanks

**Comment by jeremyshelton** [comment] 2021-08-16 08:49
@helendallas @dimasciput @aneriswanepoel 
We are having similar issues with fish data uploads, after it appeared to be fixed previously.
@helendallas today and tomorrow are public holidays in Indonesia.

**Comment by helendallas** [comment] 2021-08-25 06:48
@dimasciput PLease can you check this issue, which is a recurring one

**Comment by helendallas** [comment] 2021-09-03 08:39
@dimasciput 
Please can you update us on this issue soonest so that we know when it is fixed and we can continue uploading data

**Comment by dimasciput** [comment] 2021-09-05 04:53
@helendallas @jeremyshelton ok I'm on it

**Comment by jeremyshelton** [comment] 2021-09-05 04:57
Thanks @dimasciput

**Comment by dimasciput** [comment] 2021-09-05 07:16
@jeremyshelton @helendallas I have added the fix to testing site, will you test there first?

**Comment by dimasciput** [comment] 2021-09-05 07:16
I have cloned the database from live site to testing

**Comment by helendallas** [comment] 2021-09-06 11:52
@aneriswanepoel Please can you upload some data to testing that has the same code as an existing FBIS site, and let us know if this is working. Then Dimas can roll to live. Thanks

**Comment by jeremyshelton** [comment] 2021-09-06 13:29
I have cloned the database from live site to testing
@dimasciput thanks.
Is this something that is going to happen regularly from now on?
How often will testing be synched with live?
@helendallas

**Comment by aneriswanepoel** [comment] 2021-09-07 05:44
I have tried on testing and a new code is being made instead of using the existing one that I specified in the spreadsheet (co-ordinates also exactly the same as what is on FBIS)

Should be the existing code B7OLIF-MAMBA: 
![image](https://user-images.githubusercontent.com/55532903/132290280-57bc378a-554a-4e8b-9068-f23e03a1dc93.png)

Should be existing code X3SABI-OLIFA:
![image](https://user-images.githubusercontent.com/55532903/132290463-8ca0ea77-ad4b-4be9-9e45-05b689a56ff6.png)

Spreadsheet:
![image](https://user-images.githubusercontent.com/55532903/132290551-02cf4669-ba8b-4d00-861b-207558cf6cc1.png)

@dimasciput @helendallas @jeremyshelton

**Comment by dimasciput** [comment] 2021-09-07 06:06
thanks for the report, let me check

**Comment by dimasciput** [comment] 2021-09-07 06:10
@aneriswanepoel are these site codes not in the system previously?

**Comment by aneriswanepoel** [comment] 2021-09-07 06:13
@dimasciput they are in FBIS live but not testing. Sorry let me make another spreadsheet to upload using existing sites from Testing rather

**Comment by aneriswanepoel** [comment] 2021-09-07 06:21
@dimasciput okay tried again and it is working now

**Comment by dimasciput** [comment] 2021-09-07 06:23
ok thanks @aneriswanepoel 

@jeremyshelton @helendallas I will deploy the fix and also with the new geocontext features tomorrow morning my time, the live site will be down in a moment.

**Comment by helendallas** [comment] 2021-09-07 06:27
@dimasciput I need to work on live site today. If you deploy your time tomorrow morning that will be great as we will be sleeping.

**Comment by dimasciput** [comment] 2021-09-23 05:44
@aneriswanepoel @helendallas can we close this one?

**Comment by aneriswanepoel** [comment] 2021-09-23 06:22
> @aneriswanepoel @helendallas can we close this one?

last time I checked it is working so I think we can close

**Comment by helendallas** [comment] 2021-09-23 07:03
@dimasciput @aneriswanepoel I haven't checked recently if this is working. I wanted to but had to prepare real data first. I suggest we close this and then I will make a new ticket if the problem is persisting.

**Closed by helendallas** 2021-09-23 07:03 UTC
Labels: Uploading data
