### ISSUE TITLE
Make a Pesticide dashboard

### ISSUE THREAD

**Issue by amyburness** [kartoza/django-bims#3291] opened 2022-12-19 14:12 UTC
The pesticide dashboard needs to be made using the pesticides data  available on the system. 

This will be once a user clicks on a site within a quaternary catchment:
    • A colour coded graph showing potential risk to algae, invertebrates (Daphnia magna) and fish based on the 5 category scale (i.e. Very Low to Very High - described above).
    • Table showing the top 10 pesticides with the highest toxic unit score for algae, invertebrates and fish (expressed as a percentage of the total sum [“sum” in attribute table] of TUs for algae, invertebrates and fish, respectively).
    • A downloadable table (csv) of pesticide use giving estimated crop application rates of each pesticide per quaternary catchment in South Africa (PestApp_Quat_2014.shp attribute table).
    • Links to downloadable spreadsheets:
        ◦ We would also like a link to a spreadsheet for two Pesticide Risk Indicators (a generic one and a specific one) -  these are both excel spreadsheets that the user needs to eb able to download and use. No calculations will be done in FBIS.

**Comment by amyburness** [comment] 2022-12-21 10:38
@Fanevanjanahary Tim mentioned you are the person to help with making Dashboards in FBIS as outlined above.

**Comment by dimasciput** [comment] 2023-03-19 04:25
I'm going to close this one since it's a duplicate of https://github.com/kartoza/django-bims/issues/3320

**Closed by dimasciput** 2023-03-19 04:25 UTC
Labels: SIZE 8, Pesticide
