### ISSUE TITLE
general search FADAtims

### ISSUE THREAD

**Issue by schmikloi** [kartoza/django-bims#4294] opened 2024-10-08 13:02 UTC
hi @helendallas and @dimasciput,

I noticed that we need a general search over all organism groups; someone comes with a name, but does not know where it would belong...

**Comment by dimasciput** [comment] 2024-10-21 08:00
@schmikloi I have added the workaround to the staging site. Please give it a try.

**Comment by dimasciput** [comment] 2024-10-21 15:05
@schmikloi 

> "Enter a Latin name (or parts of it) into the search field to search for a species in all organism groups. Click on a specific box in the left menu to see all and search for species of this group."

Yes, this is the ideal way to handle it, but the current implementation is a bit different, so it will take some time to add. That's why I added the workaround.

The problem is that without a taxon group being selected, the system doesn't know if you're an expert in that group or not. Then I have to check every taxon data to see if the user can edit the taxonomy, which would overcomplicate the current workflow.

My suggestion for now is to add the text but keep the current workflow. So, the first taxon group will be selected automatically.

**Comment by schmikloi** [comment] 2024-10-23 08:43
> [@schmikloi](https://github.com/schmikloi)
> 
> > "Enter a Latin name (or parts of it) into the search field to search for a species in all organism groups. Click on a specific box in the left menu to see all and search for species of this group."
> 
> Yes, this is the ideal way to handle it, but the current implementation is a bit different, so it will take some time to add. That's why I added the workaround.
> 
> The problem is that without a taxon group being selected, the system doesn't know if you're an expert in that group or not. Then I have to check every taxon data to see if the user can edit the taxonomy, which would overcomplicate the current workflow.
> 
> My suggestion for now is to add the text but keep the current workflow. So, the first taxon group will be selected automatically.
> 
> ![Screenshot 2024-10-21 at 16 06 25](https://github.com/user-attachments/assets/20054f36-a887-47b5-8d9d-70d3a124aeeb)

@dimasciput 
Hmm, I might see it too naive, but the search should be open to everyone; only if a person is logged in, they have the right to add or edit a taxon.

**Comment by schmikloi** [comment] 2024-10-23 08:48
> [@schmikloi](https://github.com/schmikloi)
> 
> > Is it possible that the organism group expert can work in the back on their group and then decide when the public should see it?
> 
> We haven't implemented this yet. I need to think about how to handle it, it will probably take a day to implement. Maybe we can add it to the todo list for now?

@dimasciput We only can release the FADA website online once we have a solution for this; the workflow will be that I upload for example a new organism group from our template, then ask the expert to check it and then we can release it online...

**Comment by dimasciput** [comment] 2024-10-23 09:08
> Hmm, I might see it too naive, but the search should be open to everyone; only if a person is logged in, they have the right to add or edit a taxon

@schmikloi 
Okay, so the action will be hidden whether it's a user or an expert using the general search function without selecting the taxon group. Is that fine? It will probably take me half a day to implement and test it.

This means the action will only show up when the user or expert selects the taxon group. It might be a little bit confusing for the user, but this is what I can do with the limited time.

cc @helendallas

**Comment by dimasciput** [comment] 2024-10-23 09:13
> @dimasciput We only can release the FADA website online once we have a solution for this; the workflow will be that I upload for example a new organism group from our template, then ask the expert to check it and then we can release it online...

@schmikloi I understand this is an important and very useful feature, but there wasn’t any requirement for it, so I didn’t think to implement it. I can definitely add this, and it will probably take me a day to implement and test, or maybe even less.

However, could you create a new ticket for this? Since it’s not related to the current one.

I’ll ask management to give me some time to develop it.

**Comment by schmikloi** [comment] 2024-10-23 11:25
> > Hmm, I might see it too naive, but the search should be open to everyone; only if a person is logged in, they have the right to add or edit a taxon
> 
> [@schmikloi](https://github.com/schmikloi) Okay, so the action will be hidden whether it's a user or an expert using the general search function without selecting the taxon group. Is that fine? It will probably take me half a day to implement and test it.
> 
> This means the action will only show up when the user or expert selects the taxon group. It might be a little bit confusing for the user, but this is what I can do with the limited time.
> 
> cc [@helendallas](https://github.com/helendallas)

@dimasciput I am not sure if I understand what you exactly mean here with "the action will only show up..."? sorry. Could you please try to explain again. Thanks!

**Comment by helendallas** [comment] 2024-10-23 11:28
@schmikloi @dimasciput I ma also a bit confused here. Please can you explain workflow.

**Comment by schmikloi** [comment] 2024-10-23 11:35
> However, could you create a new ticket for this? Since it’s not related to the current one.

I created ticket [#4324](https://github.com/kartoza/django-bims/issues/4324) for that

**Comment by dimasciput** [comment] 2024-10-23 11:53
@helendallas @schmikloi 

![Screenshot 2024-10-21 at 16 06 25](https://github.com/user-attachments/assets/20054f36-a887-47b5-8d9d-70d3a124aeeb)

The problem is these actions depend on the taxon group, so if the expert doesn't select a taxon group, they won't show up. This is how it was implemented initially. If I have to make them show regardless of whether the expert selects a taxon group or not, I’ll have to update a lot of things.

What I propose is that it will take half a day. The user can go to the taxa management page, where they can search taxa, and it will show all species across the taxon groups. But the action buttons won't show up until they click on a taxon group first.

**Comment by schmikloi** [comment] 2024-10-23 12:33
Well, let me try to summarize...

If I am not an expert:
- I do not login
- I do not get the Add a Taxon button, which is perfectly fine
- I can search for any taxon by using the search field and get then the result in which organism group this species can be found
<img width="1993" alt="Bildschirmfoto 2024-10-23 um 14 26 37" src="https://github.com/user-attachments/assets/edaec522-df56-47fe-a8fc-b48309ca85aa">
- and am taken there if I click on the respective link in the yellow box 
<img width="1996" alt="Bildschirmfoto 2024-10-23 um 14 28 10" src="https://github.com/user-attachments/assets/defab765-0824-4398-879b-02db6957bf9e">
so this is perfectly fine!


If I am an expert:
- I do login and I am allocated to my organism group 
- I can still search for any taxon like described above
- I can only edit my group; I only need the action buttons when I am actually within my group

So I think all is fine, no?

**Comment by helendallas** [comment] 2024-11-13 10:41
As per our conversation today @dimasciput @schmikloi , it was agreed that we would leave the search as is. Improvements (estimated to take 30 hours) can only happen if additional funds are provided)

**Comment by helendallas** [comment] 2024-11-29 06:11
I am going too close this ticket as we have agree given budget constraints that we will leave as it is for now.

**Closed by helendallas** 2024-11-29 06:11 UTC
Labels: Size 40, FADAtims
