### ISSUE TITLE
Algal testing - Metadata table issue: source not available

### ISSUE THREAD

**Issue by philipfrenzel** [kartoza/django-bims#1981] opened 2020-03-20 12:01 UTC
Hi @dimasciput 

I have noticed that the source column in the metadata table is blank even though the information is in the raw data file:

On the testing site:
![image](https://user-images.githubusercontent.com/45286840/77161697-f546c400-6ab2-11ea-95aa-d33eb590358b.png)

In the raw data file:
![image](https://user-images.githubusercontent.com/45286840/77161723-05f73a00-6ab3-11ea-9cb7-7e61b7aec6fc.png)

Can you please have a look at this? Thanks. 

@helendallas  @jeremyshelton

**Comment by helendallas** [comment] 2020-03-20 12:23
@Aneri16 Please cna you assist Phil with this. It relates to the DOI, URL, or upload link. I suspect it is because the reference is not referenced correctly.

**Comment by Aneri16** [comment] 2020-03-20 12:38
@helendallas @philipfrenzel 
Usually Source doesn't have a DOI or URL etc as it just describes the source of the data (for example "University of Cape Town Masters Thesis") so I'm not sure why it isn't being pulled into FBIS... hopefully it is just a testing site issue but perhaps @dimasciput can shed some light. 
Sounds like a similar issue to that of the "Collector/Owner" column that just wasn't being pulled in/recognized correctly by FBIS

**Comment by helendallas** [comment] 2020-03-20 12:46
@Aneri16 @philipfrenzel 
If the reference has a DOI then isn't the Source field empty?

**Comment by philipfrenzel** [comment] 2020-03-20 13:03
My understanding was that if the study has a DOI, for example, then it would have the journals name as the source? I vaguely recall something this - so I'm not 100% sure.

@Aneri16  @helendallas

**Comment by dimasciput** [comment] 2020-03-20 13:30
@philipfrenzel that is because the current implementation is source only appears if it's a peer reviewed data not published data. 
![image](https://user-images.githubusercontent.com/1979569/77167895-7325c200-6ae9-11ea-8308-a6139819123a.png)

This is not a bug because it was intended to do this, if SOURCE should be displayed at all time, then I need time to update the codes.

**Comment by philipfrenzel** [comment] 2020-03-20 13:35
Thanks for clarifying @dimasciput 

I think @helendallas  would be best suited to answer whether it needs to be displayed all the time or not. Best to wait until Helen gets back to you before you make any changes to the codes.

**Comment by dimasciput** [comment] 2020-03-20 13:37
@helendallas @Aneri16 @philipfrenzel
> If the reference has a DOI then isn't the Source field empty?

Yes that's correct, because Source value is retrieved from the internet based on the DOI.

**Comment by Aneri16** [comment] 2020-03-20 18:11
Yes so "Source" should only be displayed for a report, database, or thesis. So don't need to worry if it isn't displayed for journal articles

**Comment by dimasciput** [comment] 2020-03-26 10:11
I will close this, source will still stored in database but not displayed for journal or published articles.

**Closed by dimasciput** 2020-03-26 10:11 UTC
Labels: feature-request
