### ISSUE TITLE
Source Reference search results not producing all linked sites

### ISSUE THREAD

**Issue by aneriswanepoel** [kartoza/django-bims#2702] opened 2021-07-28 12:33 UTC
When searching for this Source Reference, FBIS only shows 8 sites but there should be 21 sites:

![image](https://user-images.githubusercontent.com/55532903/127322385-fb8149f9-74fe-41bd-a1be-d3017dfe2119.png)

If you search the Owner of the data, all 21 sites are shown:

![image](https://user-images.githubusercontent.com/55532903/127322520-a73c6bd2-3658-47dd-bb5c-d048382e1008.png)

The metadata for this Owner is the same as the Source Reference searched, so FBIS should be showing all 21 sites when we search the source reference.

@dimasciput @helendallas

**Comment by helendallas** [comment] 2021-08-02 05:54
@dimasciput Here is another example of Source Reference not showing in filter even though it has been uploaded to FBIS and is shown in the metadatable

![image](https://user-images.githubusercontent.com/45286876/127810814-f91b9aed-ed63-4439-8ad7-c40138790791.png)

**Comment by helendallas** [comment] 2021-09-21 14:40
See ticket #2783 - this may be the cause of this issue since records are linked to 3 different source references

**Comment by dimasciput** [comment] 2021-09-30 03:29
@aneriswanepoel fixed in live site https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%22695%22%2C%22775%22]&endemic=&conservationStatus=[]&modules=21&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=

**Comment by jeremyshelton** [comment] 2021-10-01 11:22
@dimasciput this looks good now.
Closing ticket.

**Closed by jeremyshelton** 2021-10-01 11:22 UTC
Labels: testing, SIZE 2, Metadata, Source references, Urgent Priority 1
