### ISSUE TITLE
Develop functionality to add an embargo period for data

### ISSUE THREAD

**Issue by amyburness** [kartoza/django-bims#3606] opened 2023-11-29 12:51 UTC
Develop functionality to add an embargo period option for keeping some data private for a period of time (website and app)

**Comment by helendallas** [comment] 2024-04-18 14:04
See ticket We need to add an embargo period option for keeping some data private for a period of time #3498

https://github.com/kartoza/django-bims/issues/3498

**Comment by helendallas** [comment] 2024-04-18 14:16
Staging?

**Comment by helendallas** [comment] 2024-04-18 14:31
SO I added four frog records at a new site I created

https://sanparks.sta.do.kartoza.com/map/#search/-00117/taxon=&search=-00117&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=215601&ecosystemType=

But while I can see the site, I cannot see the data. You will recall the purpose of the embargo period is to encourage users to upload their data, which will only be visible to them until the embargo period is ended.

I set the Embargo period to 1 April 2025, but cannot see the data, only the site.

The data is in the bims table


<img width="1443" alt="Screenshot 2024-04-18 at 16 30 42" src="https://github.com/kartoza/django-bims/assets/45286876/5e00c171-7b86-4724-b110-65bc22ad8a76">

**Comment by dimasciput** [comment] 2024-04-18 14:55
@helendallas, it's been a while since I implemented this. Let me review and improve it next week.

**Comment by dimasciput** [comment] 2024-04-30 08:31
Duplicate of https://github.com/kartoza/django-bims/issues/3498, closing this one.

**Closed by dimasciput** 2024-04-30 08:31 UTC
Labels: SANParks Instance, BIMS Build Out  Implementation
